name: 'Cisco RoomOS State Action'
description: 'Cisco RoomOS Device Configuration Management using Infrastructure as Code'
inputs:
  # api-endpoint:   #ID of input
  #   description: 'The endpoint to call'
  #   required: true
  #   #default: ''
  token-data:   #github JWT Token repository secret
    description: 'JWT Token data to authenticate to the MPP service'
    required: true
runs:
  using: 'node16'
  main: 'index.js'
